### ISSUE TITLE
After submitting test file, "processes" indefinitely

### ISSUE THREAD

**Issue by mtbowers** [IBM/extract-textual-insights-from-video#6]
I followed the instructions provided in the readme file (twice) and was able to successfully launch the GUI. However, when I submit the test file Module_0_Welcome.mp4, the page just processes indefinitely. Any troubleshooting recommendations?
<img width="1792" alt="Screen Shot 2022-01-26 at 10 10 35 PM" src="https://user-images.githubusercontent.com/2035540/151301846-8617b0dc-2a80-42f6-abbe-55a020b1c562.png">

**Comment by manojjahgirdar** [comment]
@mtbowers I have updated the app, please clone the repo again and give it a try.
